# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tictactoe.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import os
import PyQt5
from PyQt5.uic import loadUi
from PyQt5 import QtWidgets,QtGui,QtCore
from PyQt5.QtWidgets import QDialog, QApplication, QWidget,QMainWindow,QLabel
from PyQt5.QtGui import QPixmap,QIcon
from PyQt5.QtCore import QTimer,QEventLoop

global Turn
Turn = True



class Ui_TicTacToeWindow(object):
    def setupUi(self, TicTacToeWindow):
        TicTacToeWindow.setObjectName("TicTacToeWindow")
        TicTacToeWindow.setFixedSize(500, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icons8-xo-xo-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TicTacToeWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(TicTacToeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 860, 621))
        self.frame.setStyleSheet("background-color:#05263B;\n"
"opacity: 0.8;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(45, 150, 416, 340))
        self.frame_2.setStyleSheet("background-color:#05263B;\n"
"opacity: 0.8;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 417, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.B1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B1.sizePolicy().hasHeightForWidth())
        self.B1.setSizePolicy(sizePolicy)
        self.B1.setStyleSheet("QPushButton:hover{\n"
"    background-color: #163B50;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    font-size: 40px;\n"
"    font-family: \"Times New Roman\";\n"
"}")
        self.B1.setText("")
        self.B1.setObjectName("B1")
        self.gridLayout.addWidget(self.B1, 1, 0, 1, 1)
        self.A3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A3.sizePolicy().hasHeightForWidth())
        self.A3.setSizePolicy(sizePolicy)
        self.A3.setStyleSheet("QPushButton:hover{\n"
"    background-color: #163B50;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    font-size: 40px;\n"
"    font-family: \"Times New Roman\";\n"
"}")
        self.A3.setText("")
        self.A3.setObjectName("A3")
        self.gridLayout.addWidget(self.A3, 0, 2, 1, 1)
        self.B3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B3.sizePolicy().hasHeightForWidth())
        self.B3.setSizePolicy(sizePolicy)
        self.B3.setStyleSheet("QPushButton:hover{\n"
"    background-color: #163B50;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    font-size: 40px;\n"
"    font-family: \"Times New Roman\";\n"
"}")
        self.B3.setText("")
        self.B3.setObjectName("B3")
        self.gridLayout.addWidget(self.B3, 1, 2, 1, 1)
        self.C2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C2.sizePolicy().hasHeightForWidth())
        self.C2.setSizePolicy(sizePolicy)
        self.C2.setStyleSheet("QPushButton:hover{\n"
"    background-color: #163B50;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    font-size: 40px;\n"
"    font-family: \"Times New Roman\";\n"
"}")
        self.C2.setText("")
        self.C2.setObjectName("C2")
        self.gridLayout.addWidget(self.C2, 2, 1, 1, 1)
        self.C1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C1.sizePolicy().hasHeightForWidth())
        self.C1.setSizePolicy(sizePolicy)
        self.C1.setStyleSheet("QPushButton:hover{\n"
"    background-color: #163B50;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    font-size: 40px;\n"
"    font-family: \"Times New Roman\";\n"
"}")
        self.C1.setText("")
        self.C1.setObjectName("C1")
        self.gridLayout.addWidget(self.C1, 2, 0, 1, 1)
        self.C3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C3.sizePolicy().hasHeightForWidth())
        self.C3.setSizePolicy(sizePolicy)
        self.C3.setStyleSheet("QPushButton:hover{\n"
"    background-color: #163B50;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    font-size: 40px;\n"
"    font-family: \"Times New Roman\";\n"
"}")
        self.C3.setText("")
        self.C3.setObjectName("C3")
        self.gridLayout.addWidget(self.C3, 2, 2, 1, 1)
        self.A1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.A1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A1.sizePolicy().hasHeightForWidth())
        self.A1.setSizePolicy(sizePolicy)
        self.A1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.A1.setFont(font)
        self.A1.setStyleSheet("QPushButton:hover{\n"
"    background-color: #163B50;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    font-size: 40px;\n"
"    font-family: \"Times New Roman\";\n"
"}")
        self.A1.setText("")
        self.A1.setObjectName("A1")
        self.gridLayout.addWidget(self.A1, 0, 0, 1, 1)
        self.B2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B2.sizePolicy().hasHeightForWidth())
        self.B2.setSizePolicy(sizePolicy)
        self.B2.setStyleSheet("QPushButton:hover{\n"
"    background-color: #163B50;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    font-size: 40px;\n"
"    font-family: \"Times New Roman\";\n"
"}")
        self.B2.setText("")
        self.B2.setObjectName("B2")
        self.gridLayout.addWidget(self.B2, 1, 1, 1, 1)
        self.A2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A2.sizePolicy().hasHeightForWidth())
        self.A2.setSizePolicy(sizePolicy)
        self.A2.setStyleSheet("QPushButton:hover{\n"
"    background-color: #163B50;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    font-size: 40px;\n"
"    font-family: \"Times New Roman\";\n"
"}")
        self.A2.setText("")
        self.A2.setObjectName("A2")
        self.gridLayout.addWidget(self.A2, 0, 1, 1, 1)
        self.MainLabel = QtWidgets.QLabel(self.frame)
        self.MainLabel.setGeometry(QtCore.QRect(110, 50, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setUnderline(False)
        self.MainLabel.setFont(font)
        self.MainLabel.setStyleSheet("\n"
"    color: white;\n"
"    font-size: 40px;\n"
"    font-family: \"Times New Roman\";\n"
"")
        self.MainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MainLabel.setObjectName("MainLabel")
        TicTacToeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TicTacToeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        TicTacToeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TicTacToeWindow)
        self.statusbar.setObjectName("statusbar")
        TicTacToeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TicTacToeWindow)
        QtCore.QMetaObject.connectSlotsByName(TicTacToeWindow)

    def retranslateUi(self, TicTacToeWindow):
        _translate = QtCore.QCoreApplication.translate
        TicTacToeWindow.setWindowTitle(_translate("TicTacToeWindow", "TicTacToe"))
        self.B1.setShortcut(_translate("TicTacToeWindow", "4"))
        self.A3.setShortcut(_translate("TicTacToeWindow", "9"))
        self.B3.setShortcut(_translate("TicTacToeWindow", "6"))
        self.A1.setShortcut(_translate("TicTacToeWindow", "7"))
        self.B2.setShortcut(_translate("TicTacToeWindow", "5"))
        self.A2.setShortcut(_translate("TicTacToeWindow", "8"))
        self.C1.setShortcut(_translate("TicTacToeWindow", "1"))
        self.C2.setShortcut(_translate("TicTacToeWindow", "2"))
        self.C3.setShortcut(_translate("TicTacToeWindow", "3"))
        self.MainLabel.setText(_translate("TicTacToeWindow", "X Turn"))
        
        #Start of my code
        #  1  2  3
        #A #  #  #
        #B #  #  #
        #C #  #  #
        self.A1.clicked.connect(self.A1GamePlaye)
        self.A2.clicked.connect(self.A2GamePlaye)
        self.A3.clicked.connect(self.A3GamePlaye)
        self.B1.clicked.connect(self.B1GamePlaye)
        self.B2.clicked.connect(self.B2GamePlaye)
        self.B3.clicked.connect(self.B3GamePlaye)
        self.C1.clicked.connect(self.C1GamePlaye)
        self.C2.clicked.connect(self.C2GamePlaye)
        self.C3.clicked.connect(self.C3GamePlaye)
        
    

    def A1GamePlaye(self):
        global Turn
        if self.A1.text()!="X" and self.A1.text()!="O":
            if Turn:
                self.A1.setText("X")
                Turn = False
                self.MainLabel.setText("O Turn")
            else:
                self.A1.setText("O")
                Turn = True
                self.MainLabel.setText("X Turn")
        winner(self)
    def A2GamePlaye(self):
        global Turn
        if self.A2.text()!="X" and self.A2.text()!="O":
            if Turn:
                self.A2.setText("X")
                Turn = False
                self.MainLabel.setText("O Turn")
            else:
                self.A2.setText("O")
                Turn = True
                self.MainLabel.setText("X Turn")
        winner(self)
    def A3GamePlaye(self):
        global Turn
        if self.A3.text()!="X" and self.A3.text()!="O":
            if Turn:
                self.A3.setText("X")
                Turn = False
                self.MainLabel.setText("O Turn")
            else:
                self.A3.setText("O")
                Turn = True
                self.MainLabel.setText("X Turn")
        winner(self)
    def B1GamePlaye(self):
        global Turn
        if self.B1.text()!="X" and self.B1.text()!="O":
            if Turn:
                self.B1.setText("X")
                Turn = False
                self.MainLabel.setText("O Turn")
            else:
                self.B1.setText("O")
                Turn = True
                self.MainLabel.setText("X Turn")
        winner(self)
    def B2GamePlaye(self):
        global Turn
        if self.B2.text()!="X" and self.B2.text()!="O":
            if Turn:
                self.B2.setText("X")
                Turn = False
                self.MainLabel.setText("O Turn")
            else:
                self.B2.setText("O")
                Turn = True
                self.MainLabel.setText("X Turn")
        winner(self)
    def B3GamePlaye(self):
        global Turn
        if self.B3.text()!="X" and self.B3.text()!="O":
            if Turn:
                self.B3.setText("X")
                Turn = False
                self.MainLabel.setText("O Turn")
            else:
                self.B3.setText("O")
                Turn = True
                self.MainLabel.setText("X Turn")
        winner(self)
    def C1GamePlaye(self):
        global Turn
        if self.C1.text()!="X" and self.C1.text()!="O":
            if Turn:
                self.C1.setText("X")
                Turn = False
                self.MainLabel.setText("O Turn")
            else:
                self.C1.setText("O")
                Turn = True
                self.MainLabel.setText("X Turn")
        winner(self)
    def C2GamePlaye(self):
        global Turn
        if self.C2.text()!="X" and self.C2.text()!="O":
            if Turn:
                self.C2.setText("X")
                Turn = False
                self.MainLabel.setText("O Turn")
            else:
                self.C2.setText("O")
                Turn = True
                self.MainLabel.setText("X Turn")
        winner(self)
    def C3GamePlaye(self):
        global Turn
        if self.C3.text()!="X" and self.C3.text()!="O":
            if Turn:
                self.C3.setText("X")
                Turn = False
                self.MainLabel.setText("O Turn")
            else:
                self.C3.setText("O")
                Turn = True
                self.MainLabel.setText("X Turn")
        winner(self)
    
def winner(self):
    global Turn
    #X win
    #horzantol line
    if (self.A1.text() =="X" and self.A2.text() =="X" and self.A3.text() =="X") or (self.B1.text() =="X" and self.B2.text() =="X" and self.B3.text() =="X") or (self.C1.text() =="X" and self.C2.text() =="X" and self.C3.text() =="X"):
        self.MainLabel.setText("X Wins")
        self.A1.setEnabled(False)
        self.A2.setEnabled(False)
        self.A3.setEnabled(False)
        self.B1.setEnabled(False)
        self.B2.setEnabled(False)
        self.B3.setEnabled(False)
        self.C1.setEnabled(False)
        self.C2.setEnabled(False)
        self.C3.setEnabled(False)
        loop = QEventLoop()
        QTimer.singleShot(2000, loop.quit)
        loop.exec_()
        Turn=True
        self.MainLabel.setText("X Turn")
        self.A1.setText("")
        self.A2.setText("")
        self.A3.setText("")
        self.B1.setText("")
        self.B2.setText("")
        self.B3.setText("")
        self.C1.setText("")
        self.C2.setText("")
        self.C3.setText("")
        self.A1.setEnabled(True)
        self.A2.setEnabled(True)
        self.A3.setEnabled(True)
        self.B1.setEnabled(True)
        self.B2.setEnabled(True)
        self.B3.setEnabled(True)
        self.C1.setEnabled(True)
        self.C2.setEnabled(True)
        self.C3.setEnabled(True)
    #vertical line
    if (self.A1.text() =="X" and self.B1.text() =="X" and self.C1.text() =="X") or (self.A2.text() =="X" and self.B2.text() =="X" and self.C2.text() =="X") or (self.A3.text() =="X" and self.B3.text() =="X" and self.C3.text() =="X"):
        self.MainLabel.setText("X Wins")
        self.A1.setEnabled(False)
        self.A2.setEnabled(False)
        self.A3.setEnabled(False)
        self.B1.setEnabled(False)
        self.B2.setEnabled(False)
        self.B3.setEnabled(False)
        self.C1.setEnabled(False)
        self.C2.setEnabled(False)
        self.C3.setEnabled(False)
        loop = QEventLoop()
        QTimer.singleShot(2000, loop.quit)
        loop.exec_()
        Turn=True
        self.MainLabel.setText("X Turn")
        self.A1.setText("")
        self.A2.setText("")
        self.A3.setText("")
        self.B1.setText("")
        self.B2.setText("")
        self.B3.setText("")
        self.C1.setText("")
        self.C2.setText("")
        self.C3.setText("")
        self.A1.setEnabled(True)
        self.A2.setEnabled(True)
        self.A3.setEnabled(True)
        self.B1.setEnabled(True)
        self.B2.setEnabled(True)
        self.B3.setEnabled(True)
        self.C1.setEnabled(True)
        self.C2.setEnabled(True)
        self.C3.setEnabled(True)
    #cross line
    if (self.A1.text() =="X" and self.B2.text() =="X" and self.C3.text() =="X") or (self.A3.text() =="X" and self.B2.text() =="X" and self.C1.text() =="X"):
        self.MainLabel.setText("X Wins")
        self.A1.setEnabled(False)
        self.A2.setEnabled(False)
        self.A3.setEnabled(False)
        self.B1.setEnabled(False)
        self.B2.setEnabled(False)
        self.B3.setEnabled(False)
        self.C1.setEnabled(False)
        self.C2.setEnabled(False)
        self.C3.setEnabled(False)
        loop = QEventLoop()
        QTimer.singleShot(2000, loop.quit)
        loop.exec_()
        Turn=True
        self.MainLabel.setText("X Turn")
        self.A1.setText("")
        self.A2.setText("")
        self.A3.setText("")
        self.B1.setText("")
        self.B2.setText("")
        self.B3.setText("")
        self.C1.setText("")
        self.C2.setText("")
        self.C3.setText("")
        self.A1.setEnabled(True)
        self.A2.setEnabled(True)
        self.A3.setEnabled(True)
        self.B1.setEnabled(True)
        self.B2.setEnabled(True)
        self.B3.setEnabled(True)
        self.C1.setEnabled(True)
        self.C2.setEnabled(True)
        self.C3.setEnabled(True)
    #O Win
    #horzantol line
    if (self.A1.text() =="O" and self.A2.text() =="O" and self.A3.text() =="O") or (self.B1.text() =="O" and self.B2.text() =="O" and self.B3.text() =="O") or (self.C1.text() =="O" and self.C2.text() =="O" and self.C3.text() =="O"):
        self.MainLabel.setText("O Wins")
        self.A1.setEnabled(False)
        self.A2.setEnabled(False)
        self.A3.setEnabled(False)
        self.B1.setEnabled(False)
        self.B2.setEnabled(False)
        self.B3.setEnabled(False)
        self.C1.setEnabled(False)
        self.C2.setEnabled(False)
        self.C3.setEnabled(False)
        loop = QEventLoop()
        QTimer.singleShot(2000, loop.quit)
        loop.exec_()
        Turn=True
        self.MainLabel.setText("X Turn")
        self.A1.setText("")
        self.A2.setText("")
        self.A3.setText("")
        self.B1.setText("")
        self.B2.setText("")
        self.B3.setText("")
        self.C1.setText("")
        self.C2.setText("")
        self.C3.setText("")
        self.A1.setEnabled(True)
        self.A2.setEnabled(True)
        self.A3.setEnabled(True)
        self.B1.setEnabled(True)
        self.B2.setEnabled(True)
        self.B3.setEnabled(True)
        self.C1.setEnabled(True)
        self.C2.setEnabled(True)
        self.C3.setEnabled(True)
    #vertical line
    if (self.A1.text() =="O" and self.B1.text() =="O" and self.C1.text() =="O") or (self.A2.text() =="O" and self.B2.text() =="O" and self.C2.text() =="O") or (self.A3.text() =="O" and self.B3.text() =="O" and self.C3.text() =="O"):
        self.MainLabel.setText("O Wins")
        self.A1.setEnabled(False)
        self.A2.setEnabled(False)
        self.A3.setEnabled(False)
        self.B1.setEnabled(False)
        self.B2.setEnabled(False)
        self.B3.setEnabled(False)
        self.C1.setEnabled(False)
        self.C2.setEnabled(False)
        self.C3.setEnabled(False)
        loop = QEventLoop()
        QTimer.singleShot(2000, loop.quit)
        loop.exec_()
        Turn=True
        self.MainLabel.setText("X Turn")
        self.A1.setText("")
        self.A2.setText("")
        self.A3.setText("")
        self.B1.setText("")
        self.B2.setText("")
        self.B3.setText("")
        self.C1.setText("")
        self.C2.setText("")
        self.C3.setText("")
        self.A1.setEnabled(True)
        self.A2.setEnabled(True)
        self.A3.setEnabled(True)
        self.B1.setEnabled(True)
        self.B2.setEnabled(True)
        self.B3.setEnabled(True)
        self.C1.setEnabled(True)
        self.C2.setEnabled(True)
        self.C3.setEnabled(True)
    #cross line
    if (self.A1.text() =="O" and self.B2.text() =="O" and self.C3.text() =="O") or (self.A3.text() =="O" and self.B2.text() =="O" and self.C1.text() =="O"):
        self.MainLabel.setText("O Wins")
        self.A1.setEnabled(False)
        self.A2.setEnabled(False)
        self.A3.setEnabled(False)
        self.B1.setEnabled(False)
        self.B2.setEnabled(False)
        self.B3.setEnabled(False)
        self.C1.setEnabled(False)
        self.C2.setEnabled(False)
        self.C3.setEnabled(False)
        loop = QEventLoop()
        QTimer.singleShot(2000, loop.quit)
        loop.exec_()
        Turn=True
        self.MainLabel.setText("X Turn")
        self.A1.setText("")
        self.A2.setText("")
        self.A3.setText("")
        self.B1.setText("")
        self.B2.setText("")
        self.B3.setText("")
        self.C1.setText("")
        self.C2.setText("")
        self.C3.setText("")
        self.A1.setEnabled(True)
        self.A2.setEnabled(True)
        self.A3.setEnabled(True)
        self.B1.setEnabled(True)
        self.B2.setEnabled(True)
        self.B3.setEnabled(True)
        self.C1.setEnabled(True)
        self.C2.setEnabled(True)
        self.C3.setEnabled(True)
    #draw
    if self.A1.text() !="" and self.B1.text() !="" and self.C1.text() !="" and self.A2.text() !="" and self.B2.text() !="" and self.C2.text() !="" and self.A3.text() !="" and self.B3.text() !="" and self.C3.text() !="":
        self.MainLabel.setText("Draw")
        self.A1.setEnabled(False)
        self.A2.setEnabled(False)
        self.A3.setEnabled(False)
        self.B1.setEnabled(False)
        self.B2.setEnabled(False)
        self.B3.setEnabled(False)
        self.C1.setEnabled(False)
        self.C2.setEnabled(False)
        self.C3.setEnabled(False)
        loop = QEventLoop()
        QTimer.singleShot(2000, loop.quit)
        loop.exec_()
        Turn=True
        self.MainLabel.setText("X Turn")
        self.A1.setText("")
        self.A2.setText("")
        self.A3.setText("")
        self.B1.setText("")
        self.B2.setText("")
        self.B3.setText("")
        self.C1.setText("")
        self.C2.setText("")
        self.C3.setText("")
        self.A1.setEnabled(True)
        self.A2.setEnabled(True)
        self.A3.setEnabled(True)
        self.B1.setEnabled(True)
        self.B2.setEnabled(True)
        self.B3.setEnabled(True)
        self.C1.setEnabled(True)
        self.C2.setEnabled(True)
        self.C3.setEnabled(True)
        #end of my code


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TicTacToeWindow = QtWidgets.QMainWindow()
    ui = Ui_TicTacToeWindow()
    ui.setupUi(TicTacToeWindow)
    TicTacToeWindow.show()
    sys.exit(app.exec_())
