/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.everthinapp1;

/**
 *
 * @author alisa
 */
public class calc extends javax.swing.JFrame {

    /**
     * Creates new form calc
     */
    public calc() {
        initComponents();
    }
    String temp="";
    String temp2="";
    String opTybe=null;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        N8 = new javax.swing.JButton();
        BBack = new javax.swing.JButton();
        BClear = new javax.swing.JButton();
        BPlus = new javax.swing.JButton();
        BDot = new javax.swing.JButton();
        N0 = new javax.swing.JButton();
        BEqual = new javax.swing.JButton();
        BMinus = new javax.swing.JButton();
        N3 = new javax.swing.JButton();
        N2 = new javax.swing.JButton();
        N1 = new javax.swing.JButton();
        BMultiplie = new javax.swing.JButton();
        N6 = new javax.swing.JButton();
        N5 = new javax.swing.JButton();
        N4 = new javax.swing.JButton();
        BDivide = new javax.swing.JButton();
        N9 = new javax.swing.JButton();
        N7 = new javax.swing.JButton();
        BBackspace = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(25, 118, 210));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        N8.setBackground(new java.awt.Color(187, 222, 251));
        N8.setIcon(new javax.swing.ImageIcon("C:\\Users\\alisa\\Documents\\NetBeansProjects\\everthinapp1\\src\\main\\java\\com\\mycompany\\everthinapp1\\icons\\Calculator\\icons8_8_100px.png")); // NOI18N
        N8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        N8.setBorderPainted(false);
        N8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N8ActionPerformed(evt);
            }
        });
        jPanel1.add(N8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 50, 50));

        BBack.setBackground(new java.awt.Color(187, 222, 251));
        BBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BBack.setForeground(new java.awt.Color(25, 118, 210));
        BBack.setText("back");
        BBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BBack.setBorderPainted(false);
        BBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBackActionPerformed(evt);
            }
        });
        jPanel1.add(BBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 80, 30));

        BClear.setBackground(new java.awt.Color(187, 222, 251));
        BClear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BClear.setForeground(new java.awt.Color(25, 118, 210));
        BClear.setText("clear");
        BClear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BClear.setBorderPainted(false);
        BClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BClearActionPerformed(evt);
            }
        });
        jPanel1.add(BClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 80, 30));

        BPlus.setBackground(new java.awt.Color(187, 222, 251));
        BPlus.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/alisa/Documents/NetBeansProjects/everthinapp1/src/main/java/com/mycompany/everthinapp1/icons/Calculator/icons8_Plus_50px.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        BPlus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BPlus.setBorderPainted(false);
        BPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPlusActionPerformed(evt);
            }
        });
        jPanel1.add(BPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 50, 50));

        BDot.setBackground(new java.awt.Color(187, 222, 251));
        BDot.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/alisa/Documents/NetBeansProjects/everthinapp1/src/main/java/com/mycompany/everthinapp1/icons/Calculator/icons8_new_moon_15px.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        BDot.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BDot.setBorderPainted(false);
        BDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDotActionPerformed(evt);
            }
        });
        jPanel1.add(BDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 50, 50));

        N0.setBackground(new java.awt.Color(187, 222, 251));
        N0.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/alisa/Documents/NetBeansProjects/everthinapp1/src/main/java/com/mycompany/everthinapp1/icons/Calculator/icons8_0_100px.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        N0.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        N0.setBorderPainted(false);
        N0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0ActionPerformed(evt);
            }
        });
        jPanel1.add(N0, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 50, 50));

        BEqual.setBackground(new java.awt.Color(187, 222, 251));
        BEqual.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/alisa/Documents/NetBeansProjects/everthinapp1/src/main/java/com/mycompany/everthinapp1/icons/Calculator/icons8_subtract_50px-removebg-preview.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        BEqual.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BEqual.setBorderPainted(false);
        BEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEqualActionPerformed(evt);
            }
        });
        jPanel1.add(BEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 50, 50));

        BMinus.setBackground(new java.awt.Color(187, 222, 251));
        BMinus.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/alisa/Documents/NetBeansProjects/everthinapp1/src/main/java/com/mycompany/everthinapp1/icons/Calculator/icons8_minus_50px.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        BMinus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BMinus.setBorderPainted(false);
        BMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMinusActionPerformed(evt);
            }
        });
        jPanel1.add(BMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 50, 50));

        N3.setBackground(new java.awt.Color(187, 222, 251));
        N3.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/alisa/Documents/NetBeansProjects/everthinapp1/src/main/java/com/mycompany/everthinapp1/icons/Calculator/icons8_3_100px_1.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        N3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        N3.setBorderPainted(false);
        N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N3ActionPerformed(evt);
            }
        });
        jPanel1.add(N3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 50, 50));

        N2.setBackground(new java.awt.Color(187, 222, 251));
        N2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/alisa/Documents/NetBeansProjects/everthinapp1/src/main/java/com/mycompany/everthinapp1/icons/Calculator/icons8_2_100px.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        N2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        N2.setBorderPainted(false);
        N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N2ActionPerformed(evt);
            }
        });
        jPanel1.add(N2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 50, 50));

        N1.setBackground(new java.awt.Color(187, 222, 251));
        N1.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/alisa/Documents/NetBeansProjects/everthinapp1/src/main/java/com/mycompany/everthinapp1/icons/Calculator/icons8_1_100px.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        N1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        N1.setBorderPainted(false);
        N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N1ActionPerformed(evt);
            }
        });
        jPanel1.add(N1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 50, 50));

        BMultiplie.setBackground(new java.awt.Color(187, 222, 251));
        BMultiplie.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/alisa/Documents/NetBeansProjects/everthinapp1/src/main/java/com/mycompany/everthinapp1/icons/Calculator/icons8_close_50px.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        BMultiplie.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BMultiplie.setBorderPainted(false);
        BMultiplie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMultiplieActionPerformed(evt);
            }
        });
        jPanel1.add(BMultiplie, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 50, 50));

        N6.setBackground(new java.awt.Color(187, 222, 251));
        N6.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/alisa/Documents/NetBeansProjects/everthinapp1/src/main/java/com/mycompany/everthinapp1/icons/Calculator/icons8_6_100px.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        N6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        N6.setBorderPainted(false);
        N6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N6ActionPerformed(evt);
            }
        });
        jPanel1.add(N6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 50, 50));

        N5.setBackground(new java.awt.Color(187, 222, 251));
        N5.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/alisa/Documents/NetBeansProjects/everthinapp1/src/main/java/com/mycompany/everthinapp1/icons/Calculator/icons8_5_100px.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        N5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        N5.setBorderPainted(false);
        N5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N5ActionPerformed(evt);
            }
        });
        jPanel1.add(N5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 50, 50));

        N4.setBackground(new java.awt.Color(187, 222, 251));
        N4.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/alisa/Documents/NetBeansProjects/everthinapp1/src/main/java/com/mycompany/everthinapp1/icons/Calculator/icons8_4_100px.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        N4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        N4.setBorderPainted(false);
        N4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N4ActionPerformed(evt);
            }
        });
        jPanel1.add(N4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 50, 50));

        BDivide.setBackground(new java.awt.Color(187, 222, 251));
        BDivide.setIcon(new javax.swing.ImageIcon("C:\\Users\\alisa\\Documents\\NetBeansProjects\\everthinapp1\\src\\main\\java\\com\\mycompany\\everthinapp1\\icons\\Calculator\\icons8_line_50px.png")); // NOI18N
        BDivide.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BDivide.setBorderPainted(false);
        BDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDivideActionPerformed(evt);
            }
        });
        jPanel1.add(BDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 50, 50));

        N9.setBackground(new java.awt.Color(187, 222, 251));
        N9.setIcon(new javax.swing.ImageIcon("C:\\Users\\alisa\\Documents\\NetBeansProjects\\everthinapp1\\src\\main\\java\\com\\mycompany\\everthinapp1\\icons\\Calculator\\icons8_9_100px.png")); // NOI18N
        N9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        N9.setBorderPainted(false);
        N9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N9ActionPerformed(evt);
            }
        });
        jPanel1.add(N9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 50, 50));

        N7.setBackground(new java.awt.Color(187, 222, 251));
        N7.setIcon(new javax.swing.ImageIcon("C:\\Users\\alisa\\Documents\\NetBeansProjects\\everthinapp1\\src\\main\\java\\com\\mycompany\\everthinapp1\\icons\\Calculator\\icons8_7_100px.png")); // NOI18N
        N7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        N7.setBorderPainted(false);
        N7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N7ActionPerformed(evt);
            }
        });
        jPanel1.add(N7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 50, 50));

        BBackspace.setBackground(new java.awt.Color(187, 222, 251));
        BBackspace.setIcon(new javax.swing.ImageIcon("C:\\Users\\alisa\\Documents\\NetBeansProjects\\everthinapp1\\src\\main\\java\\com\\mycompany\\everthinapp1\\icons\\Calculator\\icons8_eraser_34px.png")); // NOI18N
        BBackspace.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BBackspace.setBorderPainted(false);
        BBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBackspaceActionPerformed(evt);
            }
        });
        jPanel1.add(BBackspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 50, 50));

        jPanel2.setBackground(new java.awt.Color(98, 163, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(97, 176, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setBorder(null);
        jTextField1.setDisabledTextColor(new java.awt.Color(98, 163, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 320, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void N7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N7ActionPerformed
        // TODO add your handling code here:
        if (opTybe==null){
            temp=temp+"7";
            jTextField1.setText(temp);
        }else{
            temp2=temp2+"7";
            jTextField1.setText(temp+opTybe+temp2);
        }
    }//GEN-LAST:event_N7ActionPerformed

    private void N0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0ActionPerformed
        // TODO add your handling code here:
        if (opTybe==null){
            temp=temp+"0";
            jTextField1.setText(temp);
        }else{
            temp2=temp2+"0";
            jTextField1.setText(temp+opTybe+temp2);
        }
    }//GEN-LAST:event_N0ActionPerformed

    private void N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N1ActionPerformed
        // TODO add your handling code here:
        if (opTybe==null){
            temp=temp+"1";
            jTextField1.setText(temp);
        }else{
            temp2=temp2+"1";
            jTextField1.setText(temp+opTybe+temp2);
        }
        
    }//GEN-LAST:event_N1ActionPerformed

    private void N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N2ActionPerformed
        // TODO add your handling code here:
        if (opTybe==null){
            temp=temp+"2";
            jTextField1.setText(temp);
        }else{
            temp2=temp2+"2";
            jTextField1.setText(temp+opTybe+temp2);
        }
    }//GEN-LAST:event_N2ActionPerformed

    private void N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N3ActionPerformed
        // TODO add your handling code here:
        if (opTybe==null){
            temp=temp+"3";
            jTextField1.setText(temp);
        }else{
            temp2=temp2+"3";
            jTextField1.setText(temp+opTybe+temp2);
        }
    }//GEN-LAST:event_N3ActionPerformed

    private void N4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N4ActionPerformed
        // TODO add your handling code here:
       if (opTybe==null){
            temp=temp+"4";
            jTextField1.setText(temp);
        }else{
            temp2=temp2+"4";
            jTextField1.setText(temp+opTybe+temp2);
        }
    }//GEN-LAST:event_N4ActionPerformed

    private void N5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N5ActionPerformed
        // TODO add your handling code here:
        if (opTybe==null){
            temp=temp+"5";
            jTextField1.setText(temp);
        }else{
            temp2=temp2+"5";
            jTextField1.setText(temp+opTybe+temp2);
        }
    }//GEN-LAST:event_N5ActionPerformed

    private void N6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N6ActionPerformed
        // TODO add your handling code here:
        if (opTybe==null){
            temp=temp+"6";
            jTextField1.setText(temp);
        }else{
            temp2=temp2+"6";
            jTextField1.setText(temp+opTybe+temp2);
        }
    }//GEN-LAST:event_N6ActionPerformed

    private void N9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N9ActionPerformed
        // TODO add your handling code here:
        if (opTybe==null){
            temp=temp+"9";
            jTextField1.setText(temp);
        }else{
            temp2=temp2+"9";
            jTextField1.setText(temp+opTybe+temp2);
        }
    }//GEN-LAST:event_N9ActionPerformed

    private void BClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BClearActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        temp="";
        temp2="";
        opTybe=null;
    }//GEN-LAST:event_BClearActionPerformed

    private void BBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBackActionPerformed
        // TODO add your handling code here:
        NewJFrame main =new NewJFrame();
        main.show();
        
        dispose();
    }//GEN-LAST:event_BBackActionPerformed

    private void BPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPlusActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(temp+'+');
        opTybe="+";
    }//GEN-LAST:event_BPlusActionPerformed

    private void BMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMinusActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(temp+'-');
        opTybe="-";
    }//GEN-LAST:event_BMinusActionPerformed

    private void BMultiplieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMultiplieActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(temp+'*');
        opTybe="*";
    }//GEN-LAST:event_BMultiplieActionPerformed

    private void BDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDivideActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(temp+'/');
        opTybe="/";
    }//GEN-LAST:event_BDivideActionPerformed

    private void N8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N8ActionPerformed
        // TODO add your handling code here:
        if (opTybe==null){
            temp=temp+"8";
            jTextField1.setText(temp);
        }else{
            temp2=temp2+"8";
            jTextField1.setText(temp+opTybe+temp2);
        }
    }//GEN-LAST:event_N8ActionPerformed

    private void BDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDotActionPerformed
        // TODO add your handling code here:
        if (opTybe==null){
            temp=temp+".";
            jTextField1.setText(temp);
        }else{
            temp2=temp2+".";
            jTextField1.setText(temp+opTybe+temp2);
        }
    }//GEN-LAST:event_BDotActionPerformed

    private void BEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEqualActionPerformed
        // TODO add your handling code here:
        if(opTybe=="+"){
            double Dtemp=Double.parseDouble(temp)+Double.parseDouble(temp2);
            jTextField1.setText(String.valueOf(Dtemp));
            temp=String.valueOf(Dtemp);
        }
        if(opTybe=="-"){
        double Dtemp=Double.parseDouble(temp)-Double.parseDouble(temp2);
        jTextField1.setText(String.valueOf(Dtemp));
        temp=String.valueOf(Dtemp);
        }
        if(opTybe=="/"){
        double Dtemp=Double.parseDouble(temp)/Double.parseDouble(temp2);
        jTextField1.setText(String.valueOf(Dtemp));
        temp=String.valueOf(Dtemp);
        }
        if(opTybe=="*"){
        double Dtemp=Double.parseDouble(temp)*Double.parseDouble(temp2);
        jTextField1.setText(String.valueOf(Dtemp));
        temp=String.valueOf(Dtemp);
        }
        //temp="";
        temp2="";
        opTybe=null;
        
        
        
        
        
    }//GEN-LAST:event_BEqualActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBackspaceActionPerformed
        // TODO add your handling code here:
        if (opTybe==null){
            temp = temp.substring(0,temp.length() - 1);
            jTextField1.setText(temp);
        }else{
            temp2 = temp2.substring(0,temp2.length() - 1);
            jTextField1.setText(temp+opTybe+temp2);
        }
    }//GEN-LAST:event_BBackspaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBack;
    private javax.swing.JButton BBackspace;
    private javax.swing.JButton BClear;
    private javax.swing.JButton BDivide;
    private javax.swing.JButton BDot;
    private javax.swing.JButton BEqual;
    private javax.swing.JButton BMinus;
    private javax.swing.JButton BMultiplie;
    private javax.swing.JButton BPlus;
    private javax.swing.JButton N0;
    private javax.swing.JButton N1;
    private javax.swing.JButton N2;
    private javax.swing.JButton N3;
    private javax.swing.JButton N4;
    private javax.swing.JButton N5;
    private javax.swing.JButton N6;
    private javax.swing.JButton N7;
    private javax.swing.JButton N8;
    private javax.swing.JButton N9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
