# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HangMan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:#05263B;\n"
"opacity: 0.8;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GuessButton = QtWidgets.QPushButton(self.centralwidget)
        self.GuessButton.setGeometry(QtCore.QRect(270, 430, 211, 61))
        self.GuessButton.setStyleSheet("QPushButton:hover{\n"
"    background-color: #163B50;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    font-size: 40px;\n"
"    font-family: \"Times New Roman\";\n"
"}")
        self.GuessButton.setObjectName("GuessButton")
        self.WordLabel = QtWidgets.QLabel(self.centralwidget)
        self.WordLabel.setGeometry(QtCore.QRect(210, 240, 341, 71))
        self.WordLabel.setStyleSheet("\n"
"    color: white;\n"
"    font-size: 60px;\n"
"    font-family: \"Times New Roman\";\n"
"")
        self.WordLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.WordLabel.setWordWrap(False)
        self.WordLabel.setOpenExternalLinks(False)
        self.WordLabel.setObjectName("WordLabel")
        self.ArabicButton = QtWidgets.QPushButton(self.centralwidget)
        self.ArabicButton.setGeometry(QtCore.QRect(670, 20, 110, 40))
        self.ArabicButton.setStyleSheet("QPushButton:hover{\n"
"    background-color: #163B50;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-family: \"Times New Roman\";\n"
"}")
        self.ArabicButton.setObjectName("ArabicButton")
        self.EnglishButton = QtWidgets.QPushButton(self.centralwidget)
        self.EnglishButton.setGeometry(QtCore.QRect(20, 20, 110, 40))
        self.EnglishButton.setStyleSheet("QPushButton:hover{\n"
"    background-color: #163B50;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    font-size: 30px;\n"
"    font-family: \"Times New Roman\";\n"
"}")
        self.EnglishButton.setObjectName("EnglishButton")
        self.GueesInput = QtWidgets.QLineEdit(self.centralwidget)
        self.GueesInput.setGeometry(QtCore.QRect(220, 360, 300, 40))
        self.GueesInput.setStyleSheet("\n"
"color: white;\n"
"font-size: 30px;\n"
"font-family: \"Times New Roman\";\n"
"")
        self.GueesInput.setAlignment(QtCore.Qt.AlignCenter)
        self.GueesInput.setObjectName("GueesInput")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(300, 20, 180, 180))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ImageLabel = QtWidgets.QLabel(self.frame)
        self.ImageLabel.setGeometry(QtCore.QRect(0, 0, 180, 180))
        self.ImageLabel.setText("")
        self.ImageLabel.setPixmap(QtGui.QPixmap("hang10.png"))
        self.ImageLabel.setScaledContents(True)
        self.ImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ImageLabel.setWordWrap(False)
        self.ImageLabel.setIndent(-1)
        self.ImageLabel.setObjectName("ImageLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GuessButton.setText(_translate("MainWindow", "Guess"))
        self.GuessButton.setShortcut(_translate("MainWindow", "Return"))
        self.WordLabel.setText(_translate("MainWindow", "_ _ _ _ _ _"))
        self.ArabicButton.setText(_translate("MainWindow", "عربي"))
        self.EnglishButton.setText(_translate("MainWindow", "English"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
